# Generated by Django 4.2.7 on 2023-12-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
                ('Name', models.CharField(max_length=200)),
                ('Type1', models.CharField(choices=[('Normal', 'Normal'), ('Electric', 'Electric'), ('Grass', 'Grass'), ('Water', 'Water'), ('Fire', 'Fire'), ('Fighting', 'Fighting'), ('Psychic', 'Psychic')], max_length=8)),
            ],
        ),
    ]
