# Generated by Django 5.0 on 2023-12-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Normal', 'Normal'), ('Electric', 'Electric'), ('Grass', 'Grass'), ('Water', 'Water'), ('Fire', 'Fire'), ('Fighting', 'Fighting'), ('Psychic', 'Psychic')], default='Grass', max_length=8)),
                ('image', models.ImageField(upload_to='images/')),
                ('move_name', models.CharField(default='Absorb', max_length=20)),
                ('move_text', models.CharField(default='Remove 2 damage counters', max_length=200)),
                ('move_dmg', models.IntegerField(default=20)),
            ],
        ),
    ]
