# Generated by Django 4.2.7 on 2023-12-12 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcc', '0003_rename_type_pokemoncard_type1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemoncard',
            old_name='Type1',
            new_name='Type',
        ),
    ]
